### ISSUE TITLE
Unable to build docs with nightly flag

### ISSUE THREAD

**Issue by dignifiedquire** [dalek-cryptography/x25519-dalek#42] opened 2019-05-28 17:56 UTC
When building with `no-default-feautures`, `u64_backend` `std` and `nightly`

```
    Checking x25519-dalek v0.5.2
error[E0432]: unresolved import `packed_simd`
  --> /Users/dignifiedquire/.cargo/registry/src/github.com-1ecc6299db9ec823/curve25519-dalek-1.1.4/src/backend/vector/avx2/field.rs:43:5
   |
43 | use packed_simd::{i32x8, u32x8, u64x4, IntoBits};
   |     ^^^^^^^^^^^ maybe a missing `extern crate packed_simd;`?
```

**Comment by dignifiedquire** [comment] 2019-05-28 17:57
removing the `nightly` flags makes it work

**Comment by hdevalence** [comment] 2019-05-28 18:15
This is a bug in `curve25519-dalek`; the problem is that the `curve25519-dalek` docs use `doc_cfg` to build the documentation for all possible backends (including the vector backend), but the optional vector backend has a dependency on `packed_simd`.  So Rustdoc tries to build the documentation for the vector backend with a note that "this is only available with target feature blah" but fails on the missing crate, because the vector backend wasn't enabled and so its dependency wasn't pulled in.

**Comment by hdevalence** [comment] 2019-05-28 18:27
@QuietMisdreavus suggests adding a `doc` feature to `curve25519-dalek` that enables `packed_simd`

**Comment by hdevalence** [comment] 2019-05-28 18:29
Closing this issue in favor of the `curve25519-dalek` issue linked above.

**Closed by hdevalence** 2019-05-28 18:29 UTC
